server:
  port: 9090
spring:
  application:
    name: config-server
  security:
    user:
      name: nttdata
      password: nttdata$
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BootcampNttData2024/config-repository.git
          search-paths: '{application}'
          #default-label: main
